### ISSUE TITLE
Need ur tox soz....

### ISSUE THREAD

**Issue by tehroxie** [installgen2/libspurdo#2]
Hello mika.. can i add you on tox pls? soz but this is the only way i can ask for it.

**Comment by installgen2** [comment]
@tehroxie installgen2@toxme.io

**Comment by installgen2** [comment]
@tehroxie installgen2@toxme.io

**Comment by installgen2** [comment]
@tehroxie installgen2@toxme.io

**Comment by installgen2** [comment]
@tehroxie installgen2@toxme.io

**Comment by installgen2** [comment]
@tehroxie installgen2@toxme.io

**Comment by installgen2** [comment]
@tehroxie installgen2@toxme.io

**Comment by installgen2** [comment]
@tehroxie installgen2@toxme.io

**Comment by installgen2** [comment]
@tehroxie installgen2@toxme.io

**Comment by installgen2** [comment]
@tehroxie installgen2@toxme.io

**Comment by installgen2** [comment]
@tehroxie installgen2@toxme.io
